src/main/java/com/monari/monariback/location/controller/LocationController.java, src/main/java/com/monari/monariback/location/dto/LocationDto.java, src/main/java/com/monari/monariback/location/entity/Location.java, src/main/java/com/monari/monariback/location/repository/LocationRepository.java, src/main/java/com/monari/monariback/location/service/LocationService.java, src/main/resources/application.properties, src/main/resources/application.yml
=> feat: Service,Dto,Entity 설정

src/main/java/com/monari/monariback/location/controller/LocationController.java, src/main/java/com/monari/monariback/location/dto/OpenApiLocationDto.java, src/main/java/com/monari/monariback/location/dto/response/LocationResponse.java, src/main/java/com/monari/monariback/location/dto/response/OpenApiLocationResponse.java, src/main/java/com/monari/monariback/location/service/LocationService.java
> #{ISSUE_NUMBER} 
#18 
공공장소 목록을 List로 반환하는 메서드와, 공공장소의 Id 값을 받으면 해당 Id 값의 해당하는 값을 반환하는 작업을 하였습니다.
=> [장소]공공예약장소 Read 구현

src/main/java/com/monari/monariback/study/controller/StudyController.java, src/main/java/com/monari/monariback/study/dto/response/StudyResponse.java, src/main/java/com/monari/monariback/study/entity/Study.java, src/main/java/com/monari/monariback/study/repository/StudyRepository.java, src/main/java/com/monari/monariback/study/service/StudyService.java
> #21
- 스터디 상세 조회, 전체 조회 API 개발
=> [스터디] 조회 API 개발 

src/main/java/com/monari/monariback/enrollment/controller/EnrollmentController.java, src/main/java/com/monari/monariback/enrollment/dto/EnrollmentRequest.java, src/main/java/com/monari/monariback/enrollment/dto/request/EnrollmentCreateRequest.java, src/main/java/com/monari/monariback/enrollment/entity/Enrollment.java, src/main/java/com/monari/monariback/enrollment/repository/EnrollmentRepository.java, src/main/java/com/monari/monariback/enrollment/service/EnrollmentService.java, src/main/java/com/monari/monariback/global/config/error/ErrorCode.java
> #{ISSUE_NUMBER}
#23 
수강 신청 구현
=> [등록]등록 기본 구조 생성 및 기능 개발

src/main/java/com/monari/monariback/location/service/LocationService.java, src/main/resources/data.sql
> #{ISSUE_NUMBER}
#30 
SQL 더미데이터 생성
=> [공통] 더미데이터 생성

.gitignore, build.gradle, src/main/java/com/monari/monariback/enrollment/repository/EnrollmentRepository.java, src/main/java/com/monari/monariback/global/config/QueryDslConfig.java, src/main/java/com/monari/monariback/global/config/WebConfig.java, src/main/java/com/monari/monariback/global/config/error/ErrorCode.java, src/main/java/com/monari/monariback/lesson/controller/LessonController.java, src/main/java/com/monari/monariback/lesson/dto/request/CreateLessonRequest.java, src/main/java/com/monari/monariback/lesson/dto/request/SearchLessonRequest.java, src/main/java/com/monari/monariback/lesson/dto/request/UpdateLessonRequest.java, src/main/java/com/monari/monariback/lesson/dto/response/LessonResponse.java, src/main/java/com/monari/monariback/lesson/dto/response/PageInfoResponse.java, src/main/java/com/monari/monariback/lesson/entity/Lesson.java, src/main/java/com/monari/monariback/lesson/repository/LessonCustomRepository.java, src/main/java/com/monari/monariback/lesson/repository/LessonRepository.java, src/main/java/com/monari/monariback/lesson/repository/impl/LessonCustomRepositoryImpl.java, src/main/java/com/monari/monariback/lesson/service/LessonService.java, src/main/java/com/monari/monariback/teacher/repository/TeacherRepository.java, src/main/resources/data.sql
> #{ISSUE_NUMBER}
#32 
페이지네이션 구현,
검색 구현
둘 다 러프하게 진행하여 향 후 리팩토링 예정입니다.
또한 Lesson Entity에 title 이 존재하지 않아서 추가했습니다
수정한 내용이 많아서 읽어야 하는 부분이 많이 존재합니다 죄송합니다 ㅠㅠ
=> [수업] 수업 검색, 페이지네이션 구현

src/main/java/com/monari/monariback/lesson/constant/LessonResponseConstants.java, src/main/java/com/monari/monariback/lesson/constant/LessonValidationConstants.java, src/main/java/com/monari/monariback/lesson/controller/LessonController.java, src/main/java/com/monari/monariback/lesson/dto/request/CreateLessonRequest.java, src/main/java/com/monari/monariback/lesson/dto/request/SearchLessonRequest.java, src/main/java/com/monari/monariback/lesson/dto/request/UpdateLessonRequest.java, src/main/java/com/monari/monariback/lesson/dto/response/LessonResponse.java, src/main/java/com/monari/monariback/lesson/entity/Lesson.java, src/main/java/com/monari/monariback/lesson/repository/impl/LessonCustomRepositoryImpl.java, src/main/java/com/monari/monariback/lesson/service/LessonService.java, src/main/resources/data.sql
> #38  
1. QueryDsl 중복 코드 메서드 단일화
2. 컨벤션에 따른 코드 수정
3. Validation 적용
4. @Auth , @OnlyTeacher적용
=> [수업] 컨벤션에 따른 리팩토링

src/main/java/com/monari/monariback/enrollment/repository/EnrollmentCustomRepository.java, src/main/java/com/monari/monariback/enrollment/repository/impl/EnrollmentCustomRepositoryImpl.java, src/main/java/com/monari/monariback/lesson/controller/LessonController.java, src/main/java/com/monari/monariback/lesson/dto/request/SearchLessonRequest.java, src/main/java/com/monari/monariback/lesson/repository/LessonCustomRepository.java, src/main/java/com/monari/monariback/lesson/repository/impl/LessonCustomRepositoryImpl.java, src/main/java/com/monari/monariback/lesson/service/LessonService.java, src/main/resources/application.yml
> #46 
1. 학생이 참여한 수업 리스트업 구현
2. 선생이 개설한 수업 리스트업 구현
3. 검색에 필터링 구현
```java
/**
* 로그인한 사용자의 역할에 따른 수업 목록 조회 - 학생: 수강 중인 수업 - 선생님: 내가 등록한 수업
*
* @param pageNumber 페이지 번호
* @param pageSize   페이지 크기
* @param accessor   로그인 사용자 정보
* @return 수업 목록 페이지
* @author Hong
*/
@Transactional(readOnly = true)
public Page<LessonResponse> getMyEnrolledLessons(
final Integer pageNumber,
final Integer pageSize,
final Accessor accessor
) {
return switch (accessor.getUserType()) {
case STUDENT -> getLessonsForStudent(pageNumber, pageSize, accessor);
case TEACHER -> getLessonsForTeacher(pageNumber, pageSize, accessor);
case GUEST -> throw new BusinessException(ErrorCode.AUTH_FORBIDDEN);
};
}
/**
* 학생이 수강 중인 수업 목록 조회
*
* @param pageNumber 페이지 번호
* @param pageSize   페이지 크기
* @param accessor   로그인 …
```
=> [수업] 내가 참여한 수업, 내가 개설한 수업 , 필터 구현

src/main/java/com/monari/monariback/study/controller/StudyController.java, src/main/java/com/monari/monariback/study/repository/StudyCustomRepository.java, src/main/java/com/monari/monariback/study/repository/impl/StudyCustomRepositoryImpl.java, src/main/java/com/monari/monariback/study/service/StudyService.java
> #21 
- 내가 개설한 스터디 조회 API 개발
- `StudyController`와 `StudyRepository`에 해당 기능의 메서드 `getMyStudies` 구현
- `StudyCustomRepository`에 한 페이지에 반환될, 내가 개설한, 최신순 정렬된 스터디 리스트 조회하는 메서드 `findByStudentIdOrderByCreatedAtDesc`와 내가 개설한 스터디 전체 개수를 조회하는 메서드 `countByStudentId` 구현
=> [스터디] 내가 개설한 스터디 조회 API 개발

src/main/java/com/monari/monariback/common/config/WebConfig.java
=> [공통]  CORS 적용

src/main/java/com/monari/monariback/common/error/ErrorCode.java, src/main/java/com/monari/monariback/enrollment/constant/EnrollmentResponseConstants.java, src/main/java/com/monari/monariback/enrollment/controller/EnrollmentController.java, src/main/java/com/monari/monariback/enrollment/dto/response/EnrollmentResponse.java, src/main/java/com/monari/monariback/enrollment/entity/Enrollment.java, src/main/java/com/monari/monariback/enrollment/entity/enumerated/EnrollmentStatus.java, src/main/java/com/monari/monariback/enrollment/repository/EnrollmentCustomRepository.java, src/main/java/com/monari/monariback/enrollment/repository/impl/EnrollmentCustomRepositoryImpl.java, src/main/java/com/monari/monariback/enrollment/service/EnrollmentService.java, src/main/java/com/monari/monariback/lesson/dto/request/CreateLessonRequest.java, src/main/java/com/monari/monariback/lesson/dto/request/UpdateLessonRequest.java, src/main/java/com/monari/monariback/lesson/entity/Lesson.java, src/main/java/com/monari/monariback/lesson/entity/enurmerated/LessonStatus.java
> #55 
- 상태, 비용 컬럼 추가
- 결제 상태 수정 기능 추가
- 결제 최종금액 산정 기능 추가
해당 부분이 최종금액을 결정하는 메서드 입니다.
윤우님이 **스케쥴링** 하실때 이쪽으로 요청 보내주시면 될거같습니다.
```java
@PatchMapping("/{lessonId}/price")
public ResponseEntity<String> decideFinalPrice(
@PathVariable(name = "lessonId") final Integer lessonId
) {
return ResponseEntity.ok(
enrollmentService.decideFinalPrice(lessonId)
);
}
}
/**
* 수업의 수강생 수를 기준으로 수강료를 계산하여 각 학생의 최종 금액을 결정하는 메서드
*
* @param lessonId 수업 ID
* @return 최종 금액 설정 성공 메시지
* @throws BusinessException 수업이 존재하지 않거나, 수강생이 최소 인원보다 부족한 경우 발생
* @author Hong
*/
public String decideFinalPrice(final Integer lessonId) {
final Lesson lesson = lessonRepository.findById(lessonId)
.orElseThrow(() -> new BusinessException(ErrorCode.LESSON_NOT_FOUND));
List<Enrollment> enrollmentList = …
```
=> [등록] 상태, 실제 지불 비용 컬럼 추가 및 기능구현

src/main/java/com/monari/monariback/common/controller/HealthCheckController.java
> #66 
- HealthCheckController 생성
- /health 엔드포인트에서 서버 상태를 반환하도록 구현
HealthCheckController는 별도 common 패키지에서 관리 예정
/health 경로는 로드밸런서와 모니터링 도구의 헬스체크에 활용될 수 있음
=> [인프라] 인스턴스 상태 검사 API 개발

src/main/java/com/monari/monariback/location/init/LocationDataInitializer.java, src/main/java/com/monari/monariback/location/service/LocationService.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
> #71 
Local 과 Prod 환경을 분리 하였습니다.
RDS 관련 환경변수는 디스코드에 있습니다!
해당 인수를 변경함으로써 로컬과 베포환경셋팅을 정할 수 있습니다!
=> [공통] RDS 설정 및 Local Prod 환경 분리

.github/workflows/ci-cd.yml
SPRING_PROFILES_ACTIVE: prod 추가
=> [리펙토링] ci-cd.yml 수정

src/main/java/com/monari/monariback/lesson/controller/LessonController.java, src/main/java/com/monari/monariback/lesson/dto/response/LessonWithTeacherResponse.java, src/main/java/com/monari/monariback/lesson/repository/LessonCustomRepository.java, src/main/java/com/monari/monariback/lesson/repository/impl/LessonCustomRepositoryImpl.java, src/main/java/com/monari/monariback/lesson/service/LessonService.java
> #73 
Lesson Entity 에서 선생님 정보를 가져오도록 수정
=> [수업] Lesson Entity 에서 선생님 정보를 가져오도록 수정

src/main/java/com/monari/monariback/lesson/dto/response/LessonWithTeacherResponse.java, src/main/java/com/monari/monariback/lesson/service/LessonService.java
=> [수업] dto 수정

src/main/resources/application-prod.yml, src/main/resources/data.sql
- batch 메타 테이블 스키마 분리
- 메타 테이블 생성 sql MySQL로 수정
- UUID 생성 함수 MySQL 문법으로 수정
=> [chore] batch DB 설정 및 메타 테이블 sql 수정

src/main/java/com/monari/monariback/common/error/ErrorCode.java, src/main/java/com/monari/monariback/enrollment/constant/EnrollmentResponseConstants.java, src/main/java/com/monari/monariback/enrollment/controller/EnrollmentController.java, src/main/java/com/monari/monariback/enrollment/entity/Enrollment.java, src/main/java/com/monari/monariback/enrollment/entity/enumerated/EnrollmentStatus.java, src/main/java/com/monari/monariback/enrollment/repository/EnrollmentCustomRepository.java, src/main/java/com/monari/monariback/enrollment/repository/impl/EnrollmentCustomRepositoryImpl.java, src/main/java/com/monari/monariback/enrollment/service/EnrollmentService.java
> #87 
- 수업 취소 추가
- 수업 환불 요청 추가
- 수업 currentStudent 를 불러오는 로직개선
-  Status 가 환불, 환불요청, 취소가 아닌 사람들만 불러오도록 변경
=> [등록] 수업 취소, 환불 로직 추가

src/main/java/com/monari/monariback/lesson/dto/response/LessonResponse.java, src/main/java/com/monari/monariback/lesson/entity/Lesson.java, src/main/java/com/monari/monariback/lesson/service/LessonService.java, src/main/java/com/monari/monariback/location/controller/GeneralLocationController.java, src/main/java/com/monari/monariback/location/controller/LocationController.java, src/main/java/com/monari/monariback/location/dto/response/GeneralLocationResponse.java, src/main/java/com/monari/monariback/location/entity/GeneralLocation.java, src/main/java/com/monari/monariback/location/repository/GeneralLocationRepository.java, src/main/java/com/monari/monariback/location/service/GeneralLocationService.java, src/main/resources/data-local.sql
> #100 
기존에 존재했던 장소를 공공장소 PublicLocation 으로 변경
원래 존재하던 Location은 일반적인 장소, ex : studyCafe 등 으로 변경
=> [Location] 공공장소와 일반장소 나누기 

src/main/java/com/monari/monariback/batch/itemprocessor/PublicApiDataProcessor.java, src/main/java/com/monari/monariback/common/enumerated/Subject.java, src/main/java/com/monari/monariback/location/entity/Location.java, src/main/java/com/monari/monariback/location/service/LocationService.java, src/main/java/com/monari/monariback/study/dto/StudyDto.java, src/main/java/com/monari/monariback/study/dto/request/StudyCreateRequest.java, src/main/java/com/monari/monariback/study/dto/request/StudyEditRequest.java, src/main/java/com/monari/monariback/study/dto/request/StudySearchRequest.java, src/main/java/com/monari/monariback/study/dto/response/StudyDetailResponse.java, src/main/java/com/monari/monariback/study/dto/response/StudyResponse.java, src/main/java/com/monari/monariback/study/entity/Study.java, src/main/java/com/monari/monariback/study/enumerated/StudyType.java, src/main/java/com/monari/monariback/study/repository/StudyCustomRepository.java, src/main/java/com/monari/monariback/study/repository/StudyRepository.java, src/main/java/com/monari/monariback/study/repository/impl/StudyCustomRepositoryImpl.java, src/main/java/com/monari/monariback/study/service/StudyService.java, src/main/resources/data-local.sql, src/main/resources/data-prod.sql
> #103 
- 과목 enum 추가(사회, 국어, 영어)
- StudyType 추가(온라인, 오프라인)
- GeneralLocation 추가 
- GeneralLocation, Location 둘 중 하나만 입력 가능
- 둘 다 null인 경우 StudyType == ONLINE
- 서울시 시설대관 공공서비스 지역구에 해당하는 areaNm 필드 추가
- 스터디 검색 필터에 StudyType(온라인, 오프라인) 추가
추후 Location, GeneralLocation 외래키 2개 문제를 해결할 예정입니다.
=> [스터디] 4/30 회의 피드백 반영
